### ISSUE TITLE
Asas de borboleta

### ISSUE THREAD

**Issue by GeisonCamara** [GeisonCamara/avaliacao#11]
Como sugerido por vocês.

**Comment by GeisonCamara** [comment]
Não foi implementada esta função ainda, sigo no aguardo.

**Comment by bmarques1234** [comment]
Desconhecemos essa sugestão. Informamos que o projeto Geison - Fruteira do Zé foi encerrado com sucesso. Agradecemos a preferência. Att. VB desenvolvimento.
